### PR TITLE
Pin cffi to 1.13.2

### PR DESCRIPTION
**Pull request by bngcebetsha**
During v28 deployment, testing the modbus translator devices did not work correctly.. 
This indicated that the software on the new deployment was broken. 
Narrowed it down to the version of the `cffi` package.  The version that didn’t work was `cffi==1.14.5`. 
Reverted to RTS’s version:  `1.13.2`.

[JIRA: MT-2455](https://skaafrica.atlassian.net/browse/MT-2455)

### CODE REVIEW

**Review by mmphego — APPROVED** [review]
LGTM

**Review by amakhaba — APPROVED** [review]
LGTM

**Review by ajoubertza — CHANGES_REQUESTED** [review]
Good, just need the version ticked.

**Review by ajoubertza — APPROVED** [review]
LGTM

**Pull request merged**
